import { ReactNode } from 'react';

import { Link } from 'react-router-dom';
import { cn } from '../lib/cn';

export function AppLayout({ children }: { children: ReactNode }) {
  return (
    <div className='flex flex-col h-screen'>
      <div className='flex items-center justify-between px-[6px] py-[10px]'>
        <div>
          <Link to='/'>
            <img src='/assets/logo.png' height={24} alt='Logo' />
          </Link>
        </div>
        <div>
          <nav className='bg-blue-600 p-4'>
            <ul className='flex space-x-4'>
              <li>
                <Link to='/' className='text-white hover:text-blue-200'>
                  Home
                </Link>
              </li>
              <li>
                <Link
                  to='/collection'
                  className='text-white hover:text-blue-200'
                >
                  Collection
                </Link>
              </li>
              <li>
                <Link to='/contact' className='text-white hover:text-blue-200'>
                  Contact
                </Link>
              </li>
              <li>
                <Link to='/about' className='text-white hover:text-blue-200'>
                  About
                </Link>
              </li>
            </ul>
          </nav>
        </div>
      </div>
      <div className='flex-grow flex justify-center p-[6px]'>{children}</div>
      <footer className='flex items-center justify-center px-[6px] py-[10px]'>
        <aside>
          <p className={cn('text-red-700')}>
            Generated by{' '}
            <a
              href='https://fb.com/real.phongle'
              target='_blank'
              rel='noopener noreferrer'
            >
              phonglh
            </a>
          </p>
        </aside>
      </footer>
    </div>
  );
}
